name: Run Tests on Push

on:
  push:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, pdo, xml, zip, pcntl

      - name: Install Composer dependencies
        run: composer install

      - name: Create an environment file for testing
        run: cp .env.example .env.testing

      - name: Clear Configuration Cache
        run: php artisan config:clear

      - name: Generate an application key
        run: php artisan key:generate

      - name: Create a testing database
        run: |
          sleep 10 # Wait for MySQL to start
          mysql -u root -h localhost -e "CREATE DATABASE IF NOT EXISTS github_leader_board_api_db"
          php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: github_leader_board_api_db
          DB_USERNAME: root
          DB_PASSWORD: ""
