name: Run Tests on Push

on:
  push:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer dependencies
        run: composer install

      - name: Create an environment file
        run: cp .env.testing .env

      - name: Clear Configuration Cache
        run: php artisan config:clear

      - name: Generate an application key
        run: php artisan key:generate

      - name: Create a testing database
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

        env:
          DB_HOST: localhost
          DB_PORT: 3306
